name: pokemon_weakness
description: Pokemon weaknesses cheat sheet

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain:
    path: ./domain

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/icons/flying.png"

  android: "ic_launcher"
  adaptive_icon_background: "#A0A29F"
  image_path_android: "assets/icons/android/normal.png"
  adaptive_icon_foreground: "assets/icons/android/normal.png"

  ios: "Icon-App"
  image_path_ios: "assets/icons/ios/normal.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
